### PR TITLE
Enhancing the UI of the search bar

### PR DESCRIPTION
**Pull request by CODEX108**
This is fully responsive and filters data based on the project name, tech stack, and description

### CODE REVIEW

**Comment by CODEX108** [comment]
image

**Comment by CODEX108** [comment]
image

**Comment by CODEX108** [comment]
image

**Review by AlfiyaSiddique — APPROVED** [review]

**Comment by AlfiyaSiddique** [comment]
@CODEX108 approved. 👍🏻 You can merge.

**Pull request merged**
